data:
  type: TSMSDataset
  file: data/electricity/electricity.txt
  window: 168
  horizon: 6
  train_ratio: 0.6
  test_ratio: 0.2
  normalize: 3
  raw_label: False

runner:
  type: ts
  task: regression
  optimizer: Adam
  lr: 0.001
  weight_decay: 0.0
  loss_fn: mse
  metrics: [r2, rrse]
  observe: loss
  lower_is_better: True
  max_epoches: 1000
  early_stop: 30
  batch_size: 128
  aggregate: True
  
runtime:
  seed: 42
  use_cuda: true
