data:
  type: TSMSDataset
  file: data/solar-energy/solar_AL.txt
  window: 168
  horizon: 3
  train_ratio: 0.6
  test_ratio: 0.2
runner:
  type: ts
  task: regression
  optimizer: Adam
  lr: 0.001
  weight_decay: 0.0
  loss_fn: mse
  metrics: [r2, rrse]
  observe: loss
  lower_is_better: True
  max_epoches: 1000
  early_stop: 30
  batch_size: 256
  aggregate: True
runtime:
  seed: 42
  use_cuda: true
