_base_:
- ../model/itransformer.yml
- ../dataset/solar.yml
_custom_imports_:
- forecaster.network
- forecaster.dataset
- forecaster.model

data:
  raw_label: False
  window: 168
  horizon: 24
  normalize: 1
  
model:
  type: vsts
  batch_size: 32
  aggregate: False
  out_size: 24
  denormalize: True
  task: regression
  optimizer: Adam
  lr: 0.0001
  weight_decay: 0.0
  loss_fn: mse
  metrics: [r2, rrse]
  observe: loss
  lower_is_better: True
  max_epoches: 1000
  early_stop: 30
  valid_variates: 137

network:
  type: iTransformer
  d_ff: 2048
  d_model: 512
  e_layers: 12

runtime:
  output_dir: ./outputs/itransformer_horizon=24_solar_12_512_2048