_base_:
- ../model/tcn.yml
- ../dataset/solar.yml
_custom_imports_:
- forecaster.network
- forecaster.dataset
- forecaster.model

data:
  type: TSMSDataset
  raw_label: False
  horizon: 96

model:
  type: ts
  task: regression
  optimizer: Adam
  lr: 0.001
  weight_decay: 0.0
  loss_fn: mse
  metrics: [r2, rrse]
  observe: loss
  lower_is_better: True
  max_epoches: 1000
  early_stop: 30
  batch_size: 256
  aggregate: True

network:
  type: TCN
  position_embedding: False
  emb_type: learn
  kernel_size: 3
  num_levels: 3
  channel: 16
  dilation: 2
  dropout: 0.

runtime: 
  seed: 42
  output_dir: ./outputs/tcn_horizon=96_solar