_base_:
- ../model/spikegru.yml
- ../dataset/electricity.yml
_custom_imports_:
- SeqSNN.network
- SeqSNN.dataset
- SeqSNN.runner

data:
  raw_label: False
  window: 168
  horizon: 24

runner:
  type: snnvsts
  batch_size: 32
  aggregate: False
  out_size: 24
  denormalize: True
  task: regression
  optimizer: Adam
  lr: 0.0001
  weight_decay: 0.0
  loss_fn: mse
  metrics: [r2, rrse]
  observe: loss
  lower_is_better: True
  max_epoches: 1000
  early_stop: 30
  valid_variates: 321

network:
  type: ISNNGRU2d
  num_steps: 4
  layers: 1
  hidden_size: 64
  encoder_type: conv

runtime:
  seed: 42
  output_dir: ./outputs/spikegru_horizon=24_electricity