_base_:
- ../dataset/pems-bay.yml
_custom_imports_:
- SeqSNN.network
- SeqSNN.dataset
- SeqSNN.runner

data:
  window: 12
  horizon: 96
  normalize: 2
  raw_label: False

runner:
  type: ts
  task: regression
  optimizer: Adam
  lr: 0.001
  weight_decay: 0.0
  loss_fn: mse
  metrics: [r2, rse]
  observe: loss
  lower_is_better: True
  max_epoches: 1000
  early_stop: 30
  batch_size: 64
  aggregate: True

network:
  type: SpikeRNN
  hidden_size: 128
  layers: 2
  num_steps: 4
  encoder_type: conv
  # pe_type: learn
  pe_type: neuron
  pe_mode: concat
  num_pe_neuron: 40
  neuron_pe_scale: 1000.0


runtime:
  seed: 40
  output_dir: ./outputs/NeuronPE_1000_4_SpikeRNN_horizon=96_pems-bay